#+TITLE: Docs / Org-roam (v2 only)

Resources:
- [[info:org-roam#Top][org-roam#Top]] / ~C-h R org-roam~ (Org-roam User Manual)
- https://www.orgroam.com
- https://github.com/org-roam/org-roam

Note: ~C-c n …~ keys are recommended in the repo but must be bound by the user

* Basic setup

The ~org-roam-directory~ must be set first in order for org-roam to work:
: (setq org-roam-directory (file-truename "~/org-roam"))
- org-roam searches it recursively for files and maintains a cache of all
  links and nodes within

To ensure that the database gets synced automatically on startup, tracks any
changes and maintains cache consistency throughout the session:
: (org-roam-db-autosync-mode)

To build the cache manually:
: M-x org-roam-db-sync

Recommended config of the *Org-roam buffer* window:
- [[info:org-roam#Configuring the Org-roam buffer
display][org-roam#Configuring the Org-roam buffer display]].

* Nodes

A node is either a file with a top-level ID:
: :PROPERTIES:
: :ID:       <uuid-foo>
: :END:
: #+title: Foo

… or a heading withing a file with such an ID:
: * Bar
: :PROPERTIES:
: :ID:       <uuid-bar>
: :END:

To *visit* a node, which creates a new one, if it doesn’t exist:
: C-c n f : org-roam-node-find

To *capture* a node (which restores the current window config after completion),
by editing an existing node or creating a new one:
: C-c n c : org-roam-capture
- to quickly return to the captured node, use ~C-x r b : bookmark-jump~

To create a node from a *heading*, use ~M-x org-id-get-create~.

* Links

Links between nodes use Org’s standard *ID link* (e.g. ~id:foo~).

To *link to* a node at point or create one, if it doesn’t exist:
: C-c n i : org-roam-node-insert

** Completion

Use ~M-x completion-at-point~ after entering ~[[~ to insert links to nodes via
/auto-complete/.
- the completion function is ~org-roam-complete-link-at-point~, which provides
  as candidates the titles and aliases of all nodes

To use *completion anywhere* without having to enter brackets:
: (org-roam-completion-everywhere t)
- the completion function is ~org-roam-complete-everywhere~

Bind the command to ~C-M-i~ as a shortcut:
: (use-package org-roam
:   :bind (…
:          :map org-mode-map
:          ("C-M-i" . completion-at-point))
:  …)
- hit ~C-M-i~ again to cycle through nodes
- confirm selection with ~TAB~

A link inserted by /auto-complete/ at first looks like ~[[roam:My note]]~, but
turns into ~[[id:<uuid>][My note]]~ after saving the buffer.

* Org-roam buffer (Backlinks, etc.)

The *Org-roam buffer* shows relationships with other notes, e.g.:
- backlink :: ID-link to this node from another node
- reference link :: link to this node by one of its [[#refs][Refs]]
- unlinked reference :: text in another node that matches the title/alias of
  this node but is not linked to it

By default, /unlinked references/ are not shown, which can be changed in the
variable ~org-roam-mode-sections~, but may be slow.
- see [[info:org-roam#Configuring what is displayed in the buffer][org-roam#Configuring what is displayed in the buffer]]

Toggle Org-roam buffer for the current node at point:
: C-c n l : org-roam-buffer-toggle

Open Org-roam buffer for a selected node, keeping it fixed on that node:
: M-x org-roam-buffer-display-dedicated
- can be called multiple times without replacing the buffer

The buffer uses ~magit-section~ keybindings for navigation, e.g.:
- ~q~ closes the buffer
- ~p~ / ~n~ selects previous/next item
- ~RET~ visits the corresponding node
- ~TAB~ toggles section visibility
- ~M-{N}~ adjusts section visibility to level ~N~

* Tags

Set commonly used tags using the variable ~org-file-tags~.

Set tags per file node on top level header:
: #+filetags: <tag1, …>

Set tags on heading nodes as regular Org tags:
: * My heading :tag1:tag2:
- set with ~C-c C-q~ or ~C-c C-c~ (with point on headline)
- see [[file:orgMode.org::*Tags][Docs/orgMode/Tags]] for reference

Any file-level tags will be /inherited/ by heading nodes.
- inheritance can be turned off

* Aliases

Aliases are added with a special property on a node:
: :ROAM_ALIASES: <"alias 1" …>

Add aliases to node at point:
: M-x org-roam-alias-add
Remove aliases from node at point:
: M-x org-roam-alias-remove

* Refs
:PROPERTIES:
:CUSTOM_ID: refs
:END:

: :ROAM_REFS: <>

* Database
The /default/ Database since Emacs 29 is *emacsql-sqlite-builtin*
(~sqlite-builtin~). Set ~org-roam-database-connector~ to choose a different DB.
- see [[info:org-roam#How to cache][org-roam#How to cache]] for a list

If database updating is slow, set ~org-roam-db-update-on-save~ to nil, which
prevents automatic updating on file save.

Headline nodes can be excluded from the DB by setting the property:
: :ROAM_EXCLUDE: t

To exclude headlines by predicate (e.g. filter by a specific tag), set the
variable ~org-roam-db-node-include-function~ to that function.
- see [[info:org-roam#What to cache][org-roam#What to cache]]

* Graph
** org-roam-graph
The *org-roam-graph* generates images using [[https://graphviz.org][Graphviz]], which needs to be
installed and available on the /PATH/.

The variable ~org-roam-graph-executable~ holds the path to the graphing
executable:
- default value is ~"dot"~
- ~"neato"~ is an alternative, more compact graph layout

The variable ~org-roam-graph-viewer~ holds the method for viewing the graph:
- dafault is ~nil~, which uses ~view-file~
- can take a /string/ for the path to the program used or a /function/ accepting
  the graph file path as an argument

For options, see [[info:org-roam#Graph Options][org-roam#Graph Options]].

To build and (display) a graph for all nodes /or/ (with ~C-u~) just the local
graph for the current node:
: C-c n g : org-roam-graph
- add /numerical argument/ to limit node distance to ~N~ steps
- ~q~ to close graph display buffer
  
** org-roam-ui (extension)
- https://github.com/org-roam/org-roam-ui

Org-Roam-UI is a frontend for exploring and interacting with Org-roam notes.
It runs the UI as a web-app on a server using [[https://github.com/skeeto/emacs-web-server][simple-httpd]] and [[https://github.com/ahyatt/emacs-websocket][websocket]].

Basic installation & setup:
#+begin_src elisp
(use-package org-roam-ui
  :ensure t
  :after org-roam
  ;;         normally we'd recommend hooking orui after org-roam, but since
  ;;         org-roam does not have a hookable mode anymore, you're advised to
  ;;         pick something yourself if you don't care about startup time, use
  ;;         :hook (after-init . org-roam-ui-mode)
  :config
  (setq org-roam-ui-sync-theme t
	org-roam-ui-follow t
	org-roam-ui-update-on-save t
	org-roam-ui-open-on-start t))
#+end_src

Start/stop the web server with:
: M-x org-roam-ui-mode

Org-Roam-UI automatically follows visited nodes from Emacs.
- set ~(setq org-roam-ui-follow nil)~ to disable this

(manually) move /global view/ of the graph to current node:
: M-x org-roam-ui-node-zoom

Focus on just the /local graph/ of the current node:
: M-x org-roam-ui-node-local

* Citations
** org-cite
- see [[file:orgMode.org::#org-cite][org-cite]]
** org-ref (extension)
- see [[file:orgMode.org::#org-ref][org-ref (extension)]]
** citar-org-roam (extension)
- https://github.com/emacs-citar/citar-org-roam
- integrates [[file:orgMode.org::#citar][citar (extension, frontend for org-cite, etc.)]] with org-roam

** org-roam-bibtex (extension)
- https://github.com/org-roam/org-roam-bibtex
- integrates org-roam with citation systems
- allows org-roam to recognize particular nodes as bibliographic (i.e.
  associated with a particular =.bib= entry)
  
* Daily Notes
See [[info:org-roam#org-roam-dailies][org-roam#org-roam-dailies]]

Create a daily entry for /today/ / /yesterday/ / /a given date/:
: C-c n j : org-roam-dailies-capture-today
: M-x org-roam-dailies-capture-yesterday
: M-x org-roam-dailies-capture-date
- ~…yesterday~ can be given a /numeric argument/ for /n/ days in the past

Goto the daily entry for /today/ / /yesterday/ / /a given date/:
: M-x org-roam-dailies-goto-today
: M-x org-roam-dailies-goto-yesterday
: M-x org-roam-dailies-goto-date
- creates the entry if it is missing
- ~…yesterday~ can be given a /numeric argument/ for /n/ days in the future

Find and open daily notes directory:
: M-x org-roam-dailies-find-directory

Find the /previous / next/ note from an open daily entry:
: M-x org-roam-dailies-goto-previous-note
: M-x org-roam-dailies-goto-next-note
- can be given a /numeric argument/ to find /n/ days in the past/future
- /negative argument/ will reverse the direction

_Variables_

Path to daily notes: ~org-roam-dailies-directory~
- relative to ~org-roam-directory~

Capture templates: ~org-roam-dailies-capture-templates~
