#+title: Docs/Uiua

- https://www.uiua.org
- https://github.com/uiua-lang/

Online REPL: https://www.uiua.org/pad

Docs: https://www.uiua.org/docs/
- [[https://www.uiua.org/docs#tutorial][Tutorial]]
- [[https://www.uiua.org/docs/combinators][Combinators]]
- [[https://www.uiua.org/tutorial/documentation][Documenting Code]]

/Array-oriented/ programming language with a /stack-based/ execution model and a
/flat array/ model.
- arrays must be rectangular and cannot have mixed types
- mixed or deep arrays can be emulated using [[Boxes]]
- array functions use the /Leading Axis/ model

Subscripts can be added to some functions/modifiers by typing ~,~ followed by the
subscript number.
- e.g. ~?,2~ results in ~?₂~

Editor support:
- Emacs: [[https://github.com/crmsnbleyd/uiua-mode][uiua-mode]]

Install the interpreter from the latest [[https://github.com/uiua-lang/uiua/releases][GitHub release]].

Extensions:
- [[https://github.com/uiua-lang/uiua-modules][Curated list of Uiua Modules]]

* Bindings
/Bindings/ are global names that can be assigned to values:
: x ← <v>
- binding names are /case-sensitive/, they can only contain letters
- no numbers or underscores are allowed, but /subscript/ numbers at the end of
  the name (e.g. ~Foo,123~ / ~Foo₁₂₃~) are possible
- to indicate related bindings, names can end with multiple ~′~ characters
  (typed with apostrophe ~'~)
- it is recommended to use /PascalCase/ for binding names with 2+ characters to
  avoid name clashes with built-in functions and their abbreviations
- ~=~ will be converted to ~←~ by the formatter

~←~ pops the first thing off the stack and assigns it to the name on the left,
therefore it can also bind to values on previous lines:
#+begin_src uiua
×2 [2 3 4]
x ←
x  #=> [4 6 8]
#+end_src

Bindings can only bind a single value once for the entire lifetime of the
program. However, a name can be bound to another value/function:
#+begin_src uiua
X ← 42
X ## 42 
X ← @a
X ## @a 
#+end_src

But names cannot refer back to their previous values (which will be
interpreted as a recursive function):
#+begin_src uiua
X ← 12
X ## "3:1: Recursive function `X` must have a signature declared after the ←." 
X ← ×2 X
X
#+end_src


Functions can also be bound to names. If the right side of ~←~ requires more
than 0 values to be on the stack, it doesn’t get evaluated right away but will
instead be bound as a function:
: x ← <f>
- to create a 0-arity function, sorround the right side with ~()~

#+begin_src uiua
F ← +1
F5 ## 6

👋 ← ⊂"Hello, "
👋"World"
## "Hello, World"

F ← ⚂ # a value, not a function!
F ## 0.8136374781735876 
F ## 0.8136374781735876 

F′ ← (⚂) # 0-arity function
F′ ## 0.8018080663476463 
F′ ## 0.5432016624161957 
#+end_src

* Inline Functions
/Inline functions/ are defined in parentheses and are evaluated like any other
expression after being applied to their arguments. They can be broken up into
multiple lines, running from top to bottom:
#+begin_src uiua
⊸≡(+⊸⇌) [2_5_3 0_2_1 0_0_2]

X ← (
  ˙⊞=⇡ # First this line runs
  ↥⊸⇌  # Then this one
)
#+end_src

* Arrays
An array is a rectangular collection of elements arranged along some number of
axes. Nesting creates arrays of higher rank, not nested arrays (like in APL),
so all nested arrays must be of the same length.
- Uiua supports arrays with an arbitrary number of /axes/

/rows/ are the groups of elements along the /leading axis/ of an array.
- for /lists/, this is just individual elements
- in the /shape/ ~△~ of an array, the first element is the number of /rows/, which
  is also the /length/ ~⧻~ of the array

Arrays are /0-indexed/.

/Stack notation/:
: [1 2 3 4]

/Strand notation/:
: 1_2_3_4

#+begin_src uiua
[1_2_3 [4 5 6] 7_8_9]
# =>
╭─       
╷ 1 2 3  
  4 5 6  
  7 8 9  
        ╯
#+end_src

Arrays can have arbitrary code inside brackets, which is evaluated just like
any other code:
#+begin_src uiua
[×3. 4_5_6]
# =>
╭─          
╷ 12 15 18  
   4  5  6  
           ╯
#+end_src

For /pervasive functions/, the /shape/ of one array must be the /prefix/ of the
/shape/ of the other. So e.g. ~[2]~ and ~[2 3]~ are prefixes of ~[2 3 4]~, but ~[3 2]~
and ~[3]~ are not.

If shapes don’t match, a /fill item/ can be used with the /fill/ ~⬚~ modifier to
fill in the given value in missing places.

Example:
#+begin_src uiua
a ← ↯2_3 ⇡6
b ← ↯2_3_4 ⇡24
a b
### ╭─                         
### ╷ 0 1  2  3  12 13 14 15   
### ╷ 4 5  6  7  16 17 18 19   
###   8 9 10 11  20 21 22 23   
###                          ╯ 
### ╭─                         
### ╷ 0 1 2                    
###   3 4 5                    
###         ╯                  
+
## ╭─                           
## ╷  0  1  2  3  15 16 17 18   
## ╷  5  6  7  8  20 21 22 23   
##   10 11 12 13  25 26 27 28   
##                            ╯ 
#+end_src

Note: in APL, pervasive functions only apply between arrays of the same rank
or if one or both are scalar. For the example above one would have to use the
/rank/ operator: ~a (+⍤0 1) b~

Adding incompatible shapes using 100 as a /fill item/:
#+begin_src uiua
a ← ↯3_2 ⇡6
b ← ↯2_3_4 ⇡24
a b
### ╭─                         
### ╷ 0 1  2  3  12 13 14 15   
### ╷ 4 5  6  7  16 17 18 19   
###   8 9 10 11  20 21 22 23   
###                          ╯ 
### ╭─                         
### ╷ 0 1                      
###   2 3                      
###   4 5                      
###       ╯                    
⬚100+
## ╭─                                                    
## ╷   0   1   2   3   14  15  16  17  104 104 104 104   
## ╷   5   6   7   8   19  20  21  22  105 105 105 105   
##   108 109 110 111  120 121 122 123  200 200 200 200   
##                                                     ╯ 
#+end_src

* Array Boxing
Array elements with different shapes can be put into /boxes/ to emulate
nested/deep arrays:
: [□xs □ys □z …]

In the output, the elements of the boxed arrays are separated by ~|~:
: [x1 x2…|y1 y2…|∙z|…]
- scalars are marked with a ~∙~ to be distinguished from single-row lists

Instead of calling ~□~ on each item, the curly brace syntax automatically box
each item in the array:
: {x y …}

To /unbox/ the contents of a boxed array, use /un/ + /boxed/ ~°□~:
: °□boxed_x

#+begin_src uiua
□42 ## □42 

□[]    ## □[] 
°□□[]  ## [] 
□1_2   ## □[1 2] 
°□□1_2 ## [1 2] 

[□1 □2_3_4 □5_6] ## [∙1│2 3 4│5 6] 
{1 2_3_4 5_6}    ## [∙1│2 3 4│5 6] 
#+end_src

/Pervasive functions/ work on /boxed/ elements without the need to /unbox/ them.
They preserve the maximum /box depth/ of their arguments:
#+begin_src uiua
+1 4    ## 5 
+1 □4   ## □5 
+1 □□4  ## □□5 
+□□1 □4 ## □□5 

×10 {1_2_3 4_5 6} ## [10 20 30│40 50│∙60]
#+end_src

As an exception, /comparison functions/ lexicographically compare boxed arrays
as a whole:
#+begin_src uiua
= [1 2 3] [1 2 5]   ## [1 1 0] 
= □[1 2 3] □[1 2 5] ## 0 
= □[1 2 3] □[1 2 3] ## 1 
#+end_src

For /non-pervasive/ functions, the arguments often have to be /unboxed/. The
/inventory/ ~⍚~ modifier can be used to operate on temporarily /unboxed/ values.

Unboxing each boxed element in an array generally requires a way to homogenize
the elements so that the array can stay rectangular and flat.

The /content/ ~◇~ modifier takes a function and calls it on the unboxed arguments.
It can be combined with /reduce/ ~/~ to join all elements into a normal array:
#+begin_src uiua
/◇⊂{@a @b @c} ## "abc" 
/◇⊂{1 2 3} ## [1 2 3] 
#+end_src

To decompose a list of boxed elements into individual stack items, /un-box/ ~°□~
can be /subscripted/ with the exact number of elements in the list, which will
then appear one-by-one on the stack:
#+begin_src uiua
°□₃ {@a @b @c}
#### @c 
#### @b 
#### @a 
#+end_src

* Types
There are four types of arrays:
- Number
  - IEEE-754 double-precision floating-point format
  - can be written as integers, with decimals, as fractions (e.g. ~3π/2~)
  - scientific notation (e.g. ~6e3~ = ~6000~) is supported
  - can contain numeric constants like ~π~, ~τ~, ~η~, ~e~, and ~∞~
- Complex
  - printed like ~5+3i~
  - can be written as literals by suffixing the real part with ~r~ and/or the
    imaginary part with ~i~ (e.g. ~5r3i~)
  - support the same math operations as normal numbers
- Character
  - represented as 32-bit Unicode codepoints
  - character literals marked with ~@~ denote rank-0 (scalar) char arrays
  - string literals delimited by ~"…"~ denote rank-1 char arrays (strings)
  - some chars must be escaped, e.g. newline ~@\r~, null ~@\0~, but not space
  - /raw string literals/ marked with ~$~ (followed by a space) need no escaping
    - the string runs to the end of the line
    - if the next line is another raw string literal, a newline gets inserted
  - chars can also be specified with 2 (e.g. ~@\x41~) or 4 (e.g. ~@\u2665~) hex
    digits by using escape codes
    - longer/shorter sequences must be wrapped in ~{…}~ (e.g. ~@\u{1f600}~)
    - escape sequences do not work in /raw strings/
  - ~&p~ can be used for pretty-printing
- Box

The ~type~ function gets the /type/ of an array on the stack, encoded as an
integer:
- ~0~: real numbers
- ~1~: characters
- ~2~: boxes
- ~3~: complex numbers

#+begin_src uiua
type [1 2]   ## 0 
type "ab"    ## 1 
type {@a @b} ## 2 
type [i 2r1] ## 3 
#+end_src

An empty array always has the /shape/ ~[0].~ It can have different types:
#+begin_src uiua
type [] ## 0 
type "" ## 1 
type {} ## 2 
#+end_src

/Format strings/ are created by prefixing a string with ~$~. It is a special kind
of function that takes an argument for each ~_~ in the string and replaces it
with the stringified version.
- a ~_~ can be inserted by escaping it with ~/_~
- /raw strings/ can be turned into format strings with an additional ~$~.
- being functions, format strings can be used with modifiers like /reduce/

#+begin_src uiua
Oracle ← $"The meaning of _ is _!"
Oracle "life" 42
## "The meaning of life is 42!" 
Oracle @π π
## "The meaning of π is 3.141592653589793!"

3 2 1
$$ Explosion in _,
$$ _,
$$ _…
$$ BOOM!
## "Explosion in 3,\n2,\n1…\nBOOM!"

/$"_ _" {"Separated" "by" "spaces"}
## "Separated by spaces" 
#+end_src

Characters and numbers exist in an /affine space/ (like in BQN):
- ~+n c~ / ~+c n~ returns another character
- ~-n c~ returns another character
- ~-c c~ returns a number
- ~×n c~ / ~×c n~ or ~÷n c~ toggles the case of some characters, if ~n~ is negative
  - see /sign/ ~±~ to /get the case/ of a character as a number
  - see /negate/ ~¯~ to /toggle the case/ of a character
  - see /absolute value/ ~⌵~ to /uppercase/ (/lowercase/ with  ~¯⌵~) a character
- no other dyadic arithmetic operations are possible with characters

* Signatures
[[Bindings]] and [[Inline Functions]] can have a /signature/ declared like:
: … = |<input #>.<output #> …  <- for bindings
: (|<input #>.<output #> …)    <- for inline functions
- e.g. ~|2.1~ means the function takes 2 arguments and returns one
- the second number is optional and defaults to 1 if not given

A /declared/ signature always overrides the /inferred/ signature. If they don’t
match, there will be a warning.

* Modules

Import a function from a local module:
: ~ "<filename>" ~ <fn-name>
and call it like this:
: <fn-name> …

Import the local module as a namespace, using an alias:
: <alias> ~ "<filename>"
and call a function from it like this:
: <alias>~<fn-name>

* Comments
A comment ~#~ with additional ~#~'s is an /output comment/. Each additional ~#~ prints
the next item from the top of the stack on /format/. This is useful for
debugging.

#+begin_src uiua
# Normal comments

1 2 # inline

# Output comments

1 2 3
####

+ 3 4 ##

# the formatter turns it into:
1 2 3
#### 3
#### 2
#### 1

+ 3 4 ## 12
#+end_src

Output comments inside [[Inline Functions][inline functions]] will show the values for each time the
function is called.
#+begin_src uiua
F ← (
  ## 5 6
  + 1 ## 6 7 
)
F 5
F 6

#+end_src

* Constants
- ~η~ eta (pi/2; tau/4)
- ~π~ pi (2 eta; tau/2)
- ~τ~ tau (2 pi; 4 eta)
- ~∞~ infinity
- ~i~ imaginary number

* Functions
** Stack Functions
*** ~?~ stack [noa., 0-out] & ~ₙ~
Prints all stack values at insertion, without popping them.

With a /subscript/, will print only that number of values from the stack.

*** ~∘~ identity [mon.] {id / i(→planet)}
Does nothing with one value (monadic).

#+begin_src uiua
∘ 5
# =>
5
#+end_src

*** ~◌~ pop [mon., 0-out] {po / p(→planet)} & ~°~
Discards the top stack value.

** Monadic Pervasive
*** ~¬~ not
Logical /not/ operation.
- equivalent to ~-⊙1~ → subtracts the number from 1

*** ~¯~ negate {neg}
Negates a number.
- like monadic ~-~ (negate) in APL
- backtick ~`~ will be converted to a /negate/ ~¯~ by the formatter
*** ~±~ sign {sig / sgn}
Returns the numeric sign (~1~, ~¯1~ or ~0~).

On a *complex number*, /normalizes/ it to magnitude 1.

On a *character*, gets its case:
- ~¯1~ for /lowercase/
- ~1~ for /uppercase/
- ~0~ for /caseless/

#+begin_src uiua
± "A new WORLD" ## [1 0 ¯1 ¯1 ¯1 0 1 1 1 1 1] 
#+end_src
*** ~⌵~ absolute value {abs}
Returns the /absolute value/ of the number.

With *complex numbers*, converts them to their /magnitude/.

With *characters*, /capitalizes/ them.
*** ~√~ sqrt {sqr}
Returns the /square root/ of the number.
- with a /subscript n/, returns the *nth root*
- ~√¯1~ = ~NaN~, but ~√ℂ0¯1~ = ~i~
*** ~ₑ~ exponential {exp} & ~°~ logarithm {log} & ~ₙ~
Returns the exponential /e^x/ for the number /x/:
: ₑ x
- set the base /b/ per /subscript/ to get /b^x/
  - same as ~ⁿ x b~

The /un/ ~°~ modifier returns the /natural logarithm/ instead:
: °ₑ x
- set the base /b/ per /subscript/ to get /log_b(x)/

*** ~∿~ sine {sin} & ~°~
Returns the /sine/ of the number.

~∿+η~ gets the /cosine/ instead.

~°∿~ gets the /arcsine/, ~˜-η°∿~ gets the /arccosine/.

Also see /un-atangent/ ~°∠~ to get both /sine/ and /cosine/ together. Note that
for ~η~, there are tiny differences between the two methods that may lead to
inconsistent results:
#+begin_src uiua
TrigA ← ⊂⊃∿ (∿+η) # sin cos
TrigA η ## [1 0.00…012246467991473532] 
TrigA π ## [0.00…012246467991473532 ¯1] 
TrigA τ ## [¯0.00…024492935982947064 1] 

TrigB ← ⊂°∠
TrigB η ## [1 0.00…06123233995736766] 
TrigB π ## [0.00…012246467991473532 ¯1] 
TrigB τ ## [¯0.00…024492935982947064 1] 

≍ ⊃TrigA TrigB η ## 0 
≍ ⊃TrigA TrigB π ## 1 
≍ ⊃TrigA TrigB τ ## 1 
#+end_src
*** ~⌊~ ~⌈~ ~⁅~ floor {flr}, ceil {cei}, round {rou} & ~ₙ~
Rounds to the nearest integer /(round)/: towards ~¯∞~ /(floor)/ or towards ~∞~
/(ceil)/.

/round/ with fraction ~0.5~ will round away from 0
- e.g. ~⁅2.5 = 3~ and ~⁅¯2.5 = ¯3~

/round/ with a /subscript/ rounds to that many decimal places.

** Dyadic Pervasive
*** ~+~ ~-~ add, subtract {sub}
Adds/subtracts two values.

/un-add/ ~°+~ splits a number into fractional and integer parts:
#+begin_src uiua
[°+ 1/3]   ## [0.333… 0] 
[°+ 3/2]   ## [0.5 1] 
[°+ 2.5]   ## [0.5 2] 
[°+ ¯5.25] ## [0.75 ¯6] 
#+end_src

*** ~×~ ~÷~ multiply {mul, ~*~} & ~⍜°~, divide {div} & ~°~

Division by 0 results in infinity ~∞~.

*** ~ⁿ~ power {pow}
Raises the second value to the /power/ of the first.

/anti-backward-power/ (~⌝˜ⁿ)~ or /un-exponential/ (~°ₑ~) can be used to get the
*logarithm* of a number.

*** ~◿~ modulo {mod}
Returns the remainder of dividing the second by the first argument.

Use ~⍜⊙⌵◿~ to get /negative modulo/ instead of /remainder/:
#+begin_src uiua
x ← ˜-↻1⊂⟜⇡×2 .5
x
◿ 3 x
⍜⊙⌵◿ 3 x
# =>
[¯5 ¯4 ¯3 ¯2 ¯1 0 1 2 3 4 5]
[1 2 0 1 2 0 1 2 0 1 2]
[¯2 ¯1 ¯0 ¯2 ¯1 0 1 2 0 1 2]
#+end_src
*** ~∠~ atangent {ata} & ~°~
Returns the /arctangent/ of two numbers.

The /inverse/ ~°∠~ puts both, the /cosine/ and /sine/ (in that order) of the input
angle onto the stack. Therefore, ~˜÷°∠~ gets the /tangent/ of the angle.

#+begin_src uiua
a ← ⊞˜∠ ⇌.[¯ 1 0 1]
a # angle
## ╭─
## ╷  3τ/8  η  τ/8
##       π  0    0
##   ¯3τ/8 ¯η ¯τ/8
##                 ╯
∩⁅₂ °∠ a # cos(a) | sin(a)
### ╭─
### ╷ ¯0.71 0 0.71
###   ¯1    1 1
###   ¯0.71 0 0.71
###                ╯
### ╭─
### ╷  0.71  1  0.71
###    0     0  0
###   ¯0.71 ¯1 ¯0.71
###                  ╯
⁅₂ ˜÷°∠ a # tan(a)
## ╭─
## ╷ ¯1  16331239353195368  1
##   ¯0                  0  0
##    1 ¯16331239353195368 ¯1
##                            ╯
#+end_src
*** ~=~ ~≠~ equals {eq}, not equals {~!=~ / ne / neq}
Compare for equality/inequality.
- Uiua has no boolean type. Comparison operators return ~0~ for /false/ and ~1~
  for /true/.

*** ~<~ ~>~ less than {lt}, greater than {gt}
Compares for less/greater than.
- ~< x y~ means ~y < x~
- ~> x y~ means ~y > x~

*** ~≤~ ~≥~ less or equal {~<=~ / le / leq}, greater or equal {~>=~ / ge / geq}
Compares for less/greater than or equal.
- ~≤ x y~ means ~y ≤ x~
- ~≥ x y~ means ~y ≥ x~

*** ~↥ ↧~ maximum {max}, minimum {min}
Takes the max./min. of two arrays.
- like dyadic ~⌈~ (maximum) / ~⌊~ (minimum) in APL
*** ~ℂ~ complex {com} & ~°~
Creates a complex number from an /imaginary/ and a /real/ part on the stack.
- stack order: 1. /imaginary/ 2. /real/
- equivalent to ~+×i~

/un-complex/ ~°ℂ~ pushes the /imaginary/ and /real/ parts back on the stack (in
the same order as the input to /complex/).

#+begin_src uiua
ℂ 3 5 ## 5+3i
[°ℂ] i ## [1 0]
= 5 ℂ0 5 ## 1
#+end_src

See also:
- /absolute value/ ~⌵~ → get the magnitude
- /sign/ ~±~ → normalize to magnitude 1

** Monadic Array
*** ~⧻~ length {len} & ~(°⊸)ₙ~
Returns the number of items along the first axis of the array.
- like monadic ~≢~ (tally) in APL

*** ~△~ shape {sha} & ~°ₙ⍜~
Returns the dimensions of the array.
- like monadic ~⍴~ (shape) in APL

#+begin_src uiua
△5               #=> []
△[]              #=> [0]
△[9 1 6]         #=> [3]
△[4_π_9 1_5_∞]   #=> [2 3]
△[[1_2_3 3_4_5]] #=> [1 2 3]
#+end_src

/un-shape/ ~°△~ takes a /shape/ as input and returns an array of that shape.

#+begin_src uiua
°△ 2_3_4
## ╭─                         
## ╷ 0 1  2  3  12 13 14 15   
## ╷ 4 5  6  7  16 17 18 19   
##   8 9 10 11  20 21 22 23   
##                          ╯ 
#+end_src

*** ~♭~ deshape {flat / des} & ~⍜~
Flattens the array to /rank 1/.
- like monadic ~,~ (ravel) in APL

With a /subscript/, flattens it to /rank n/.
- /negative subscripts/ flatten to rank /m-n/ (relative to rank /m/ of the arr.)
- if the subscript rank is greater than the rank of the array, /length-1/
  axes are added to the front of the shape
- if the subscript is 0, returns the first scalar in the array

#+begin_src uiua
△ ♭ °△2_3_4_5  ## [120] 
△ ♭₂ °△2_3_4_5 ## [24 5] 
△ ♭₃ °△2_3_4_5 ## [6 4 5]

△ ♭₋₁ °△2_3_4_5 ## [6 4 5] 
△ ♭₋₂ °△2_3_4_5 ## [24 5] 
△ ♭₋₃ °△2_3_4_5 ## [120] 
#+end_src

/under-deshape/ ~⍜♭<f>~ flattens the array, applies a function and puts it
back to its original shape. This can be useful to reverse higher-ranked
arrays:
#+begin_src uiua
⊸⍜♭⇌ ↯3_4⇡12
### ╭─            
### ╷ 0 1  2  3   
###   4 5  6  7   
###   8 9 10 11   
###             ╯ 
### ╭─            
### ╷ 11 10 9 8   
###    7  6 5 4   
###    3  2 1 0   
###             ╯ 
#+end_src

*** ~⊢~ ~⊣~ first {fir} & ~⍜ₙ~, last {las} & ~⍜ₙ~
Returns the first/last /row/ (first axis) of an array.
- like dyadic ~1↑~ / ~¯1↑~ (take) in APL
- with /subscript/, puts that many rows/elements on the stack
  - stack order is reversed for /last/

*** ~⊚~ where {whe} & ~°~
Returns an array of indices where array values are not equal to ~0~.
- like monadic ~⍸~ (where) in APL
- e.g. to get indices from a binary mask
- works with multi-dimensional arrays (result is always rank 2)
- on a list it is equivalent to ~˜▽°⊏~
- for boolean masks, /select where/ ~⊏⊚~ is equivalent to /keep/ ~▽~

#+begin_src uiua
⊸⊚ > 4 [2 8 3 9 1 7 2]
### [0 1 0 1 0 1 0] 
### [1 3 5]         

⊸⊚ > 4 [2_8_3 9_1_7]
### ╭─        
### ╷ 0 1 0   
###   1 0 1   
###         ╯ 
### ╭─        
### ╷ 0 1     
###   1 0     
###   1 2     
###       ╯   
#+end_src

/un-where/ ~°⊚~ takes an array of indices (can be unordered) and returns an
array of counts at the position each index indicates.
#+begin_src uiua
°⊚ [3 2 8 2 2 5]
## [0 0 3 1 0 1 0 0 1] 

°⊚ [3_4 2_1 0_3]
## ╭─            
## ╷ 0 0 0 1 0   
##   0 0 0 0 0   
##   0 1 0 0 0   
##   0 0 0 0 1   
##             ╯ 
#+end_src

/under-where/ ~⍜⊚~ allows for manipulation of the index array from /where/
before it is inverted (via /un-where/) to an array of positions based on
these indices.
#+begin_src uiua
[1_1_0 0_1_1 0_1_1]
⍜⊚(▽≡/×¬⊸◿2)
## ╭─        
## ╷ 1 0 0   
##   0 0 0   
##   0 0 1   
##         ╯ 
#+end_src

*** ~⇡~ range {ran} & ~ₙ~
Creates an array of all natural numbers less than /n/.
- like monadic /index generator/ (iota) ~⍳~ in APL

/range/ with /subscript/ changes the /offset/ of the range:
#+begin_src uiua
⇡₁ 5 ## [1 2 3 4 5] 
⇡₂ 5 ## [2 3 4 5 6] 
#+end_src

*** ~⇌~ reverse {rev}
Reverses the array along the first axis.
- like monadic ~⊖~ (reverse first) in APL
- ~≡⇌~ behaves like monadic ~⌽~ (reverse) in APL
  
*** ~⍉~ transpose {tra} & ~°~
Transposes/rotates the axes/shape of the array so that the /leading axis/
will become the /last axis/ of the shape.
- like monadic ~⍉~ (transpose) in APL
- e.g. the shape of ~⍉°△5_4_3_2_1~ will become ~[4 3 2 1 5]~

#+begin_src uiua
⍉ [1_2_3
   4_5_6]
## ╭─
## ╷ 1 4
##   2 5
##   3 6
##       ╯
#+end_src

/un-transpose/ ~°⍉~ instead rotates the /last axis/ to become the /leading axis/
of the shape.
- e.g. the shape of ~°⍉°△5_4_3_2_1~ will become ~[1 5 4 3 2]~

#+begin_src uiua
X ← °△2_3_4
X # 2×3×4
## ╭─
## ╷ 0 1  2  3  12 13 14 15
## ╷ 4 5  6  7  16 17 18 19
##   8 9 10 11  20 21 22 23
##                          ╯
⍉ X # 3×4×2
## ╭─
## ╷ 0 12  4 16   8 20
## ╷ 1 13  5 17   9 21
##   2 14  6 18  10 22
##   3 15  7 19  11 23
##                     ╯
°⍉ X # 4×2×3
## ╭─
## ╷  0  4  8   1  5  9   2  6 10   3  7 11
## ╷ 12 16 20  13 17 21  14 18 22  15 19 23
##                                          ╯
#+end_src

*** ~¤~ fix {fx / f(→planet)}
Adds a /length-1/ axis to the array.

*** ~□~ box {bx} & ~°(⍜°)ₙ~
See [[Array Boxing]].

*** ~⋯~ bits & ~°⍜ₙ~
Encode a number/array as bits (LSB-first).
- “LBS” means /least significant bit/
- always results in an array 1 rank higher than the input
- with /subscript/, forces the number of bits to be used (extends or
  truncates the bits)

/un-bits/ ~°⋯~ decodes bits back to numbers.

*Warning:* conversion (~⋯~ / ~°⋯~) on large numbers (> 53 bits long) may give
incorrect results due to floating point imprecision.

/under-bits/ ~⍜⋯~ performs /bit-wise operations/.

** Dyadic Array
*** ~↯~ reshape {res} & ~⬚~
Reshape the array to fit the given shape.
- like ~⍴~ (reshape) in APL
- repeats elements when overcounting the input array (like in APL)
*** ~↻~ rotate {rot} & ~⬚⍜~
Rotates the elements of the array by /n/ places /left-//upwards/.
- like dyadic ~⌽~ (rotate) in APL

/under-rotate/ ~⍜↻<f>~ rotates the array, applies a function to it and
reverses the rotation:
#+begin_src uiua
⍜(↻3|⊂0) [1 2 3 4 5] ## [1 2 3 0 4 5] 
#+end_src

*** ~⤸~ orient {ori} & ~⬚(⍜⌝)°⌝~
Changes the order of the axes of the array given a list of unique /axis
indices/.
- ~⤸¯1~ is equivalent to /un-transpose/ ~°⍉~

*** ~↙~ ~↘~ take {tak} & ~⬚(°⬚)~, drop {dro} & ~⬚⌝~
Takes/drops /n/ elements along the first axis of the array.
- like dyadic ~↑~ (take) / ~↓~ (drop) in APL

With a given /fill/ ~⬚~ item, any excess amount /taken/ will add that many fill
items to the array:
#+begin_src uiua
⬚@.↙10 "Iverson"  ## "Iverson..." 
⬚@.↙¯10 "Iverson" ## "...Iverson" 
#+end_src

Similarly, /anti-drop/ ~⌝↘~ pads an array with /n/ fill elements:
- uses a default fill item, when no /fill/ ~⬚~ modifier is given
#+begin_src uiua
⬚@.⌝↘¯3 "Iverson" ## "Iverson..." 
⬚@.⌝↘3 "Iverson"  ## "...Iverson" 

↘2 [1 2 3 4 5]        ## [3 4 5] 
⌝↘2 [1 2 3 4 5]       ## [0 0 1 2 3 4 5] 

↘ 1_2 [1_2_3_4
       5_6_7_8]
## ╭─
## ╷ 7 8
##       ╯
⌝↘ 1_2 [1_2_3_4
        5_6_7_8]
## ╭─
## ╷ 0 0 0 0 0 0
##   0 0 1 2 3 4
##   0 0 5 6 7 8
##               ╯
#+end_src

/under-take/ / /under-drop/ ~⍜↙<f>~ ~⍜↘<f>~ takes/drops items from the array,
calls a function on them and puts them back into the array:
#+begin_src uiua
⍜(↙2)/× [3 5 4 2] ## [15 4 2] 
#+end_src

*** ~⊡~ pick {pic} & ~°⍜⌝~
Picks a /row/ or /element/ of the array, given a single index or a list of
indices (to reach into higher-ranked arrays).

If the index array is /rank 2/ or greater, multiple rows or elements will be
picked:
#+begin_src uiua
⊡ 1 [1_2_3 4_5_6]         ## [4 5 6] 
⊡ 1_1 [1_2_3 4_5_6]       ## 5 
⊡ [1_2 0_1] [1_2_3 4_5_6] ## [6 2] 
#+end_src

/anti-pick/ ~⌝⊡~ inserts the elements of an array at their corresponding
indices:
- requires a /fill/ ~⬚~ value if not all indices are present
#+begin_src uiua
⬚@-⌝⊡ 3 @a ## "---a" 
⬚0⌝⊡ 2 [1 2 3 4]
## ╭─
## ╷ 0 0 0 0
##   0 0 0 0
##   1 2 3 4
##           ╯
⬚@X⌝⊡ [1 2] ["cat" "eye"]
## ╭─
## ╷ "XXX"  "XXX"  "XXX"
## ╷ "XXX"  "XXX"  "XXX"
## ╷
##   "XXX"  "XXX"  "cat"
##   "XXX"  "XXX"  "eye"
##                       ╯
⬚@X⌝⊡ [1_1 0_3] ["cat" "eye"]
## ╭─
## ╷ "XXX"  "XXX"
## ╷ "XXX"  "cat"
##   "XXX"  "XXX"
##   "eye"  "XXX"
##                ╯
⌝⊡ 0_0_0 "ab"
## ╭─       
## ╷        
## ╷ "ab"   
## ╷        
##        ╯ 
#+end_src

/un-pick/ ~°⊡~ enumerates the indices of the array:
- equivalent to /range-by-shape/ ~⇡⊸△~
#+begin_src uiua
°⊡ "wow"
### "wow"
### ╭─
### ╷ 0
###   1
###   2
###     ╯
°⊡ ["pow" "wow"]
### ╭─
### ╷ "pow"
###   "wow"
###         ╯
### ╭─
### ╷ 0 0  1 0
### ╷ 0 1  1 1
###   0 2  1 2
###            ╯
#+end_src

/under-pick/ ~⍜⊡<f>~ picks an item from the array, applies a function on it
and puts it back into the original array:
- if the values passed to /under/ are not constants, they can be put
  outside, in a different order
- to replace the value at the index, use /pop/ ~◌~ or /gap/ ~⋅~
#+begin_src uiua
⍜(⊡2|×10) [1 2 3 4] ## [1 2 30 4]
⍜⊡× 2 [1 2 3 4] 10 ## [1 2 30 4]

⍜(⊡2)⋅∞ [1 2 3 4] ## [1 2 ∞ 4] 
⍜⊡◌ 2 [1 2 3 4] ∞ ## [1 2 ∞ 4] 
#+end_src

*** ~⊏~ select {sel} & ~⬚°⍜⌝~
Selects /rows/ from an array according to an index vector.
- like an index selection ~arr[…]~ or the idiom ~⊂⍛⌷~ in Dyalog APL

/anti-select/ ~⌝⊏~ creates an array where each element of the input array is
arranged according to the given index vector:
- a /fill/ ~⬚~ modifier can be attached to fill empty positions
- without a /fill/, it is essentially a permutation

#+begin_src uiua
⊏ [2 0 1 1] "abc"   ## "cabb" 
⬚@-⌝⊏ [5 2 1] "bcf" ## "-fc--b" 
⌝⊏ [2 0 1] "abc"    ## "bca" 
#+end_src

/un-select/ ~°⊏~ produces an array of indices for the rows of the input array
while leaving it on the stack:
#+begin_src uiua
°⊏ "enumerate"
### "enumerate"         
### [0 1 2 3 4 5 6 7 8] 

≡°⊏ ["hello" "world"]
### ╭─            
### ╷ "hello"     
###   "world"     
###           ╯   
### ╭─            
### ╷ 0 1 2 3 4   
###   0 1 2 3 4   
###             ╯ 
#+end_src

/under-select/ ~⍜⊏<f>~ selects items from the array, applies a function on
them and puts them back into the original array.
- works similar to /under-pick/

*** ~▽~ keep {kee} & ~⊸⬚°ₙ⍜⌝~
Discards or copies items in an array:
: ▽ <mask> <arr>
- like dyadic ~⌿~ (replicate first) in APL

Example:
#+begin_src uiua
▽ [0 1 0 1] [1_2 3_4 5_6 7_8]
#=>
╭─     
╷ 3 4  
  7 8  
      ╯
#+end_src

~⍜▽~ modifies part of an array according to a mask:
: ⍜▽<f> <mask> <arr>

Example:
#+begin_src uiua
⍜▽(×.) [0 1 1 0 1] [1 2 3 4 5]
#=>
[1 4 9 4 25]
#+end_src

*** ~⌕~ find
Returns a boolean array that marks (the start of) each occurrence of the
first array in the second.
- like dyadic ~⍷~ (find) in APL

*** ~⦷~ mask
*** ~∊~ memberof {mem / elem}
Checks if each row in the second array exists in the first one and returns
an array of boolean numbers.
- like dyadic ~∊~ (membership) in APL (arg. order swapped!)

#+begin_src uiua
∊ [1 2 3] 2           ## 1 
∊ [1 2 3] 4           ## 0 
∊ [0 3 4 5 1] [1 2 3] ## [1 0 1] 
∊ [3 4 5] [1_2_3 4_5_6]
## ╭─
## ╷ 0 0 1
##   1 1 0
##         ╯
#+end_src

/keep-by-memberof/ ~▽⊸∊~ gets the /intersection/ of two arrays/sets.

*** ~⊗~ indexin {idx / ind} & ~⬚~
Finds the first index in the first array of each row of the second array.
- like dyadic ~⍳~ (index of) in APL, except that this only applies to /major
  cells/ for higher-ranked arrays, while /indexin/ applies to each /k-cell/ of
  the first arg. for a second arg. of rank /k/
- returns the /length/ of the searched-in array if the index cannot be found
  or a /fill-item/ if the /fill/ ~⬚~ modifier is specified

#+begin_src uiua
⨂ [1 2 3] 2     ## 1 
⨂ [1 2 3] [2 3] ## [1 2] 

⨂ [[1_2 3_4] [5_6 7_8]] 4
## ╭─
## ╷ 2 1
##   2 2
##       ╯
⨂ [[1_2 3_4] [5_6 7_8]] [3 4]
## [1 2]
#+end_src

*** ~≍~ match
*** ~⊂~ join {joi} & ~⬚°ₙ~
Concatenates two arrays or appends a new /row/ in case of a scalar.
- like dyadic ~⍪~ (catenate first) in APL
- ~≡⊂~ behaves like dyadic ~,~ (catenate) in APL

*** ~⊟~ couple {cou} & ~⬚°ₙ~
Combine two arrays as /rows/ of a new array (increases the rank).
- with a /subscript/, more than 2 arrays can be coupled
- can be combined with /rows/ ~≡~ to couple pairs of rows from both arrays

#+begin_src uiua
⊟ 1 2       ## [1 2] 
⊟₃ @f @u @n ## "fun" 
⊟ [1 2 3] [4 5 6]
## ╭─
## ╷ 1 2 3
##   4 5 6
##         ╯
≡⊟ [1 2 3] [4 5 6]
## ╭─
## ╷ 1 4
##   2 5
##   3 6
##       ╯
#+end_src

/un-couple/ ~°⊟~ separates combined arrays:
#+begin_src uiua
°⊟ [1 2]
### 2 
### 1 

°⊟ [0_1_2
    3_4_5]
### [3 4 5] 
### [0 1 2] 

≡°⊟₃ [0_1_2
      3_4_5]
#### [2 5] 
#### [1 4] 
#### [0 3] 
#+end_src

/fill/ ~⬚~ completes the coupled array when shapes don’t match:
#+begin_src uiua
⬚@ ⊟ "Apple" "Pie"
## ╭─          
## ╷ "Apple"   
##   "Pie  "   
##           ╯ 
#+end_src

*** ~⊥~ base
Returns the base digits of the number in the second argument, given a
single base or a list of bases for each digit in the first argument.
- like binary ~⊤~ (encode) in APL, except that the shape of the output shape
  is reversed and each number reads from left to right instead rtl. So
  prepending ~⇌⍉~ makes them equal
- digits are listed /least-significant/ to /most-significant/ and are
  represented by integers only (no letters)
- with a list of bases, any unlisted remaining digit will be truncated
  - an ~∞~ at the end of the list collects the remainder in that “digit”

#+begin_src uiua
⊥ 2 38       ## [0 1 1 0 0 1] 
⊥ [2 2 2] 38 ## [0 1 1] 
⊥ [2 2 ∞] 38 ## [0 1 9] 

⊥ 16 18      ## [2 1] 

⊥ 2 ⇡ⁿ2 3
## ╭─
## ╷ 0 0 0 0
##   1 0 0 0
##   0 1 0 0
##   1 1 0 0
##   0 0 1 0
##   1 0 1 0
##   0 1 1 0
##   1 1 1 0
##   0 0 0 1
##           ╯
#+end_src

** Misc
*** ~repr~ {rpr}
Converts a value to its code representation.

*** ~&ims~ image - show
Shows an image, depending on the system backend.

*Note:* In the (Ghostty) terminal, the image does not always shows up with
lower row/column lengths (bug?).
- better use /window mode/ ~-w~ for graphic output
*** ~&gifs~ gif - show
*** ~&ap~ audio - play
*** ~&s~ show
Prints a nicely formatted representation of a value to stdout.

Array axes are layed out in an alternating horizontal→vertical→… pattern.
The elements of the last axis are always layed out horizontally
(column-wise), the ones on the next axis vertically (row-wise), for the
next axis it is horizontally again, etc.
- this is different to APL, where every axis before the last one is layed
  out vertically in rows

*** ~&p~ print with newline
Print a value to stdout followed by a newline.
* Modifiers (→Operators)
** Stack Modifiers
*** ~˜~ backward [mon.] {bac}
Swaps the arguments of a dyadic function.
- like monadic operator ~⍨~ (commute) in APL

: ˜ -3 10  =  -10 3  =  -7

*** ~˙~ self [mon.] {slf}
Calls a function with the same array as all arguments.

#+begin_src uiua
˙+ 5
# =>
10

˙⊞+ 1_2_3
# =>
╭─       
╷ 2 3 4  
  3 4 5  
  4 5 6  
        ╯
#+end_src

*** ~⊙~ dip [mon.] {d(→planet)}
Temporarily pops the top value off the stack and calls the function.
- stacking multiple /dips/ enables operating on lower stack values without
  touching the top ones

#+begin_src uiua
⊙+ 1 2 3 4
# =>
4
5
1

[⊙⊙+ 1 2 3 4]
# =>
[1 2 7]

⊙(/↥) 1_2_3 4_5_6
# =>
6
[1 2 3]
#+end_src

Combines well with /fork/ ~⊃~ to keep values on the stack after/before
operating on them:
- use /gap/ ~⋅~ to drop subsequent stack values
#+begin_src uiua
[⊃⊙⊙∘(++) 3 5 10]
# =>
[3 5 10 18]

[⊃⊙⋅∘(++) 3 5 10]
# =>
[3 10 18]
#+end_src

*** ~⋅~ gap [mon.] {ga / g(→planet)}
Discards the top stack value before calling the function.
- also see the function /pop/ ~◌~

#+begin_src uiua
⋅+ 3 5 10
# =>
15
#+end_src

*** ~⊃~ fork [dya.] {for / f(→planet)}
Calls two functions on the same value(s) and puts both outputs on the
stack.
- the functions can be of any arity; if one function takes fewer
  arguments, it just uses that many arguments from the top of the stack
- always executes the right branch before the left
- important for threading data through a program and for /planet notation/

#+begin_src uiua
⊃⇌⧻ 1_2_3_4
# =>
4
[4 3 2 1]

⊃↧↥ ⇡4 ⇌⇡4
# =>
[3 2 2 3]
[0 1 1 0]
#+end_src

With a /function pack/, /fork/ can take any number of functions instead of
just two:
#+begin_src uiua
[⊃(+|-|×|÷) 2 5]
## [7 3 10 2.5] 
#+end_src

*** ~∩~ both [mon.] {bot} & ~ₙ⌞⌟~
Calls the /n/-ary function on two sequences of the next top /n/ values on the
stack.
- just the top 2 values in case of a unary function
- for a dyadic function ~f~ on ~a b c d~, calls ~f a b~ and ~f c d~

#+begin_src uiua
∩⇡ 4 6
### [0 1 2 3 4 5]
### [0 1 2 3]
[∩+ 1 2 3 4] ## [3 7] 
#+end_src

With /numbered subscripts/, /both/ calls its function on /n/ sets of arguments:
#+begin_src uiua
[∩₃⊟ 1 2 3 4 5 6]
## ╭─      
## ╷ 1 2   
##   3 4   
##   5 6   
##       ╯ 
#+end_src

/both/ can be used with /sided subscripts/ to apply the /left-most/ ~⌞~ or
/right-most/ ~⌟~ argument twice:
#+begin_src uiua
[∩⊟ @a @b @c @d]
## ╭─       
## ╷ "ab"   
##   "cd"   
##        ╯ 
[∩⌞⊟ @a @b @c]
## ╭─       
## ╷ "ab"   
##   "ac"   
##        ╯ 
[∩⌟⊟ @a @b @c]
## ╭─       
## ╷ "ac"   
##   "bc"   
##        ╯ 
#+end_src

/sided/ and /numeric subscripts/ can also be mixed.

*** ~⊓~ bracket [dya.] {bra} & ~⌞⌟~
Calls two /n/-ary functions on two sequences of the next top /n/ values on the
stack.
- just the top 2 values in case of a unary function
- for dyadic functions ~f~ and ~g~ on ~a b c d~, calls ~f a b~ and ~g c d~

Like /fork/, /bracket/ can take any number of functions instead of just two
when using a /function pack/:
#+begin_src uiua
[⊓(+|-|×|÷) 10 20 5 8 3 7 2 5]
## [30 3 21 2.5] 
#+end_src

/bracket/ (like /both/) can be used with /sided subscripts/ to apply the
/left-most/ ~⌞~ or /right-most/ ~⌟~ argument twice:
#+begin_src uiua
{⊓⊟□₂ @a @b @c @d}
## ["ab"│[@c│@d]] 
{⊓⌞⊟□₂ @a @b @c}
## ["ab"│[@a│@c]] 
{⊓⌟⊟□₂ @a @b @c}
## ["ac"│[@b│@c]] 

⊓⌟≥≤5 8 [6 2 5 9 6 5 0 4]
### [1 1 1 0 1 1 1 1] 
### [1 0 1 1 1 1 0 0] 
#+end_src

*** ~⟜~ ~⤚~ on, off [mon.]
Keeps the first argument before /(on)/ / behind /(off)/ the output.

*** ~⊸~ ~⤙~ by, with {wit} [mon.]
Keeps the last argument behind /(by)/ / before /(with)/ the output.

With /with/, multiple dyadic functions can be called with the same last
argument:
#+begin_src uiua
+1⤙×2 5
### 10 
### 6  
#+end_src

Combined with /planet notation/, /with/ can copy or move items lower in the
stack to the top:
#+begin_src uiua
[⤙⊙⊙⊙∘ 1 2 3 4] ## [4 1 2 3 4] 
[⤙⊙⊙⊙◌ 1 2 3 4] ## [4 1 2 3] 
[⤙⊙⊙∘ 1 2 3 4]  ## [3 1 2 3 4] 
[⤙⊙⊙◌ 1 2 3 4]  ## [3 1 2 4] 
#+end_src

*** ~◠~ ~◡~ above {abo}, below {bel} [mon.]

** Iterating Modifiers
*** ~≡~ rows [mon.] {row} & ~ₙ⌞⌟~
Applies the function to /each row/ of the array(s).
: ≡<f> <arr …>
- similar to monadic operator ~¨~ (each) in APL

Using a /numeric subscript/ specifies the /rank/ of the subarrays the function
operates on:
- this is equivalent to stacking multiple ~≡~
- positive subscripts count from bottom to top
- negative subscripts count from top to bottom, like normal/stacked ~≡~
#+begin_src uiua
≡₀□ °△ 2_3_4 # Scalars <=> ≡₋₃□ <=> ≡≡≡□
## ┌─
## ╷ ∙0│∙1│∙2 │∙3 ║∙12│∙13│∙14│∙15
## ╷ ──┼──┼───┼───╫───┼───┼───┼───
##   ∙4│∙5│∙6 │∙7 ║∙16│∙17│∙18│∙19
##   ──┼──┼───┼───╫───┼───┼───┼───
##   ∙8│∙9│∙10│∙11║∙20│∙21│∙22│∙23
##                                 ┘
≡₁□ °△ 2_3_4 # Vectors <=> ≡₋₂□ <=> ≡≡□
## ┌─
## ╷ 0 1 2 3    │4 5 6 7    │8 9 10 11
##   ───────────┼───────────┼───────────
##   12 13 14 15│16 17 18 19│20 21 22 23
##                                       ┘
≡₂□ °△ 2_3_4 # Matrices <=> ≡₋₁□ <=> ≡□
## ┌─
##   0 1  2  3│12 13 14 15
##   4 5  6  7│16 17 18 19
##   8 9 10 11│20 21 22 23
##                         ┘
≡₃□ °△ 2_3_4
##  ╭─
##  ╷ 0 1  2  3  12 13 14 15
## □╷ 4 5  6  7  16 17 18 19
##    8 9 10 11  20 21 22 23
##                           ╯
#+end_src

With a /sided subscript/, either the first ~⌞~ or the last ~⌟~ argument will be
/fix/'ed ~¤~:
- can be followed by a number to specify how many arguments to fix
- can be combined with a /numeric subscript/ before the /sided subscr./
#+begin_src uiua
≡⌞⊂ "ro" "wt" # reuses "ro" 
## ╭─
## ╷ "row"
##   "rot"
##         ╯
≡⌟⊂ "cm" "at" # reuses "at"
## ╭─
## ╷ "cat"
##   "mat"
##         ╯

≡⌞₂(⊂⊂) 1_2 3_4 5_6
## ╭─            
## ╷ 1 2 3 4 5   
##   1 2 3 4 6   
##             ╯ 
≡⌟₂(⊂⊂) 1_2 3_4 5_6
## ╭─            
## ╷ 1 3 4 5 6   
##   2 3 4 5 6   
##             ╯

⤚≡₂⌟₁□₃ °△2_2_3 "hi" "there"
### ╭─                      
### ╷ 0 1 2  6  7  8        
### ╷ 3 4 5  9 10 11        
###                  ╯      
### ┌─                      
### ╷ 0 1 2  │∙@h│"there"   
###   3 4 5  │   │          
###   ───────┼───┼───────   
###   6  7  8│∙@i│"there"   
###   9 10 11│   │          
###                       ┘ 
#+end_src

*** ~⊞~ table [mon.] {tab}
Applies ~f~ on all combinations of rows from arrays ~a~ and ~b~:
: ⊞<f> <a> <b>
- there seems to be no analog in APL, /outer product/ only works scalar-wise
- always operates on the rows /(leading axis)/, regardless of the ranks

#+begin_src uiua
⊞(⊂⇌) [1_2 3_4] [5 6 7]
#=>
╭─              
╷ 2 1 5  4 3 5  
╷ 2 1 6  4 3 6  
  2 1 7  4 3 7  
               ╯
#+end_src

*** ~⧈~ stencil [mon.] {st} & ~⬚ₙ~
Applies function ~f~ on /shape/-~s~ sized /sliding windows/ of the array:
: ⧈<f><s> <arr>
- scalar sizes can also be specified by /subscript/
- if ~f~ is not /monadic/, window size will be determined by its arity

With a window size of ~[[n]]~, stencil can be used to partition an array
into equally-sized chunks:
#+begin_src uiua
⧈□[[2]] "lorem ipsum"
## ["lo"│"re"│"m "│"ip"│"su"] 
⬚@ ⧈□[[3]] "lorem ipsum"
## ["   "│"   "│"lor"│"em "│"ips"│"um "│"   "] 
#+end_src

*** ~⧅~ tuples [mon.] {tup} & ~⬚ₙ~

: ⧅<f><n> <arr>

*** ~⍚~ inventory [mon.] {inv}
Applies the function to each /unboxed/ row of an array and re-/boxes/ the
result.
: ⍚<f>

*** ~⍥~ repeat [mon.] {rep}
Iterates a function ~n~ times.
: ⍥<f> <n>

/repeat/ can be used to conditionally call a function when ~n~ gets replaced
with a predicate. The returned boolean will either call the function 0 or
1 times:
#+begin_src uiua
F ← ⍥(×10)⊸<10
F 5  ## 50 
F 12 ## 12 
#+end_src

*** ~⍢~ do [dya.]
Repeatedly calls ~f~ as long as the ~condition~ function returns ~1~.
- the condition is evaluated first (like a /while loop)/
- only way to do an infinite loop in Uiua (using ~1~ as the ~condition~)
- array ops are almost always faster, so only use when necessary
: ⍢(<f>|<condition>)

If ~f~ is part of the ~condition~ instead of the first argument (which is then
the identity function), ~⍢~ can be used as a /do-while/ loop instead:
#+begin_src uiua
# as a while loop:
⍢(⊂+1⊸⊢|<3⊢) [3] ## [3] 
# as a do-while loop:
⍢(∘|⊙⊂⊸<3+1⊸⊢) [3] ## [4 3] 
#+end_src

Depending on the /net signature/ of the /composed signature/ from the two
input functions, either:
- arguments will be reused (net negative)
- nothing else happens (net 0)
- last outputs get collected in an array (net positive)
#+begin_src uiua
[⍢(+1|>) 0 10]    # Net negative, 10 is reused
⍢(+1|<10) 0       # Net 0, just calls functions
⍢(⤚(+₁⊙∘)|>) 0 10 # Net positive, last outputs collected
#### [10 10]
#### 10
#### [0 1 2 3 4 5 6 7 8 9]
#+end_src
- example modified from [[https://discord.com/channels/1156339038748413952/1156817423048118343/1454927866218414325][Uiua Discord]] (posted by Kaikalii)

** Aggregating Modifiers
*** ~/~ reduce [mon.] {red}
Applies reducing function ~f~ to the array (“between” its items):
: /<f> <arr>
- reduces along the /first/ axis (across columns in a matrix)
- like monadic op. ~⌿~ (reduce first) in APL
*** ~\~ scan [mon.] {sca}
Like /reduce/ ~/~, but keeps intermediate values.
: \<f> <arr>
- scans along the /first/ axis (across columns in a matrix)
- like monadic op. ~⍀~ (scan first) in APL

Use the ~⬚~ /fill/ operator to add a different initial value.

*** ~∧~ fold [mon.] {fol}
*** ~⊕~ group [mon.] {gro} & ~°⍜⬚~
Splits the array into groups of items matching the same integer in a given
~indices~ list and applies function ~f~ to each group.
: ⊕<f> <indices> <arr>
- kind-of like dyadic ~⌸~ (key) in APL, but keys would be implicit as
  indices of the matrix rows and there is no nested array
  - maybe together with /classify/ ~⊛~ it behaves more like key
- the resulting array is ordered by the indices in the list
- indices/keys less than 0 are omitted

The values returned by the function must all have the same /shape/ to be
properly concatenated in the resulting array. If this is not the case, a
/fill/ ~⬚~ item can be provided to fix the shapes:
#+begin_src uiua
⬚∞⊕∘ [0 1 0 2 1 1] [1 2 3 4 5 6]
## ╭─        
## ╷ 1 3 ∞   
##   2 5 6   
##   4 ∞ ∞   
##         ╯ 
#+end_src

Or just /box/ ~□~ each group to encapsulate different shapes:
#+begin_src uiua
⊕□ [0 1 0 2 1 1] [1 2 3 4 5 6]
## [1 3│2 5 6│4] 
#+end_src

*** ~⊜~ partition [mon.] {par} & ~°⍜⬚~
Groups sequential sections of ~arr~ according to a ~markers~ list of integers
and applies function ~f~ to each group.
: ⊜<f> <markers> <arr>
- like dyadic ~⊆~ (partition) in APL, except ~⊆~ doesn’t take a function
- markers don’t imply any ordering, they can be any integer
  - e.g. the list can be a boolean mask ~[1 1 0 0 1 1 0 0]~
- markers less than or equal to 0 are omitted
- both arguments must be the same length

The values returned by the function must all have the same /shape/ to be
properly concatenated in the resulting array. If this is not the case, a
/fill/ ~⬚~ item can be provided to fix the shapes:
#+begin_src uiua
⬚∞⊜∘ [0 2 3 3 3 0 1 1] [1 2 3 4 5 6 7 8]
## ╭─        
## ╷ 2 ∞ ∞   
##   3 4 5   
##   7 8 ∞   
##         ╯ 
#+end_src

Or just /box/ ~□~ each partition to encapsulate different shapes:
#+begin_src uiua
⊜□ [0 2 3 3 3 0 1 1] [1 2 3 4 5 6 7 8]
## [2│3 4 5│7 8] 

⊜□ ⊸≠@  $ Hey there friendo
## ["Hey"│"there"│"friendo"] 
#+end_src

The idiom ~⍜⊜□⍚<f>~ can be used to apply an operation to partitions of an
array before restoring the original array structure:
#+begin_src uiua
⍜⊜□⍚⇌⊸≠@  "get in the racecar" ## "teg ni eht racecar" 
#+end_src

** Inversion Modifiers
*** ~°~ un [mon.]
Inverts the behaviour of a function.
- e.g. for /un-boxing/: ~°□~
- the inverse must always have the opposite signature of the function
  - e.g. signature ~|2.1~ must become ~|1.2~

/un-by/ ~°⊸<f>~ applies the “undo” part of a function’s /under/ ~⍜~ inverse
without the “do” part.
- works only for /monadic/ functions

#+begin_src uiua
⍜⊢(×10) [2 3 4] ## [20 3 4] 
°⊸⊢ 0 [2 3 4]   ## [0 3 4] 

⍜(⊡2)(⋅5) [1 2 3 4] ## [1 2 5 4] 
°⊸(⊡2) 5 [1 2 3 4]  ## [1 2 5 4] 
#+end_src

*** ~⌝~ anti [mon.] {ant}
Inverts the behaviour of a function, treating its first argument as a
constant(?)
- similar to /un/ ~°~, but allows the use of external arguments
- for dya. func. ~F~ and values ~A~ and ~B~, ~⌝F A B~ is equivalent to ~°(F A) B~
- the /anti inverse/ of a function with signature ~|a.b~ is ~|(b+1).(a-1)~
  - e.g. signature ~|2.1~ will stay ~|2.1~

*** ~⍜~ under [dya.] {und}
Operates (~g~) on a transformed (~f~) array, then reverses the transformation.
: ⍜<f><g>
- more powerful version of /un/ ~°~

*** ~⌅~ obverse [mon.] {obv}
Defines inverses of a function.

** Other Modifiers
*** ~⬚~ fill {fil}
Fill missing values of an array that has mismatched shapes with ~fill-value~
so it becomes a valid array:
: ⬚<fill-value> <arr/f>
- partially like monadic ~↑~ (mix) in APL, but not with nested arrays and with
  function argument

#+begin_src uiua
⬚0[1 2_3_4 5_6]
#=>
╭─       
╷ 1 0 0  
  2 3 4  
  5 6 0  
        ╯

⬚π↙ 5 [1 2 3]
#=>
[1 2 3 π π]
#+end_src
*** ~⨬~ switch [dya.] {sw}
Calls either ~f~ or ~g~ depending on the given ~index~ (selector).
- may also take a /function pack/ to switch between more than 2 functions
- the function signatures do not need to match exactly, any excess args
  will be discarded
: ⨬<f><g> <index>

The ~index~ can also be a list of indices, in which case a list of results
from the functions selected by each index is returned for each
corresponding input /row/ (similar to /rows/ ~≡~).
- indices may be repeated, which just calls the same function again
- in this case, the shapes of all returned values must match
#+begin_src uiua
⨬+- 0 [1 2 3] [4 5 6]       ## [5 7 9] 
⨬+- [1 0 1] [1 2 3] [4 5 6] ## [3 7 3]

⨬(+|-|×|÷) [1 2 0 3] 2 5       ## [3 10 7 2.5] 
⨬(+|-|×|÷) [1 2 0 3] ↯4 2 ↯4 5 ## [3 10 7 2.5] 
#+end_src

/switch/ can be used to write a switch expression like in non-array
languages using /index-in/ ~⨂~ to find the index of the first true predicate:
#+begin_src uiua
F ← ⨬("small"|"medium"|"large")˜⨂1⊂⊃(<₁₀|<₁₀₀)
# or equivalently:
F = ⨬("small"|"medium"|"large")/+≥[10 100]

F 3   ## "small" 
F 13  ## "medium" 
F 113 ## "large" 
#+end_src

/switch/ can be used to write /recursive functions/, where the selector would
be a predicate to match the base-case ~g~ or recur with ~f~ otherwise.
- should be avoided if there is an array-based or iterative solution
- (note that factorial is more idiomatic with ~/×⇡₁~)
#+begin_src uiua
Fact ← |1 ⨬(×Fact⊸-1|1)⊸<2
Fact 5 ## 120 
#+end_src

*** ~⍣~ try [dya.]
Attempts to call ~f~ and, if an error is thrown, calls a ~catch~ function to
handle it with the original arguments and the error value as input.
: ⍣<f><catch>

#+begin_src uiua
⍣⋕0 "5"   ## 5 
⍣⋕0 "dog" ## 0 
#+end_src

*** ~⍤~ assert [dya.]
Throws an error (with given ~message~) if a condition is not met, i.e. if
the ~test-value~ is anything but ~1~.
- can be used to write tests
- just prints, but does not return anything
: ⍤<message> <test-value>

Use /self-assert/ ~˙⍤~ to ignore the message part:
: ˙⍤ <test-value>

Thrown errors can be caught with /try/ ~⍣~.

With the /semantic comment/ ~# Track caller!~, the error message can refer to
the call site instead of to the code of the /assert/ function itself for
more useful error messages.

* Pattern Matching
See https://www.uiua.org/tutorial/Pattern%20Matching

The /un/ ~°~ modifier can be applied to constants to pattern-match them. If the
constant is not equal to the argument, an error is thrown. Otherwise, the
argument is popped from the stack.

Using /planet notation/, arrays can be destructured to match certain values and
extract others:
#+begin_src uiua
°[1⊙3] [1 5 3]             ## 5 
°[1 2⊙⊙(5∘)] [1 2 3 4 5 6] #### 6 
                           #### 4 
                           #### 3 
°[1_2 [⊙4]] [1_2 3_4]      ## 3 
#+end_src

/un-join/ ~°⊂~ with a constant can be used to match arrays with a certain
/prefix/ or /suffix/ (using /backward/ ~˜~):
#+begin_src uiua
°(⊂1) [1 2 3] ## [2 3]
°(˜⊂3) [1 2 3] ## [1 2] 
#+end_src

* Macros
*Index Macros*

*Code Macros*

* Idioms/Recipes
Sources:
- https://www.uiua.org/docs/idioms
- https://tankorsmash.unison-services.cloud/s/uiuisms-service/

Duplicate a value on the stack:
: ⟜∘

“wrench” — turn boolean list into list of -1/1:
: -⊸¬

Create an inclusive range from [n,m]:
: ⍜(⌵-|⇡+₁) <n> <m>

Get a function signature via a macro:
: SigOf! ←^ ⋅⊢
use like:
: SigOf!<f>

Check if all rows in an array are equal:
: ≍⊸↻1

Create an array of indices with the given ~shape~:
: °△<shape>

Get prime factors of a number:
: °/×
Check if a number is prime:
: =1⧻°/×

Successively intersperse ~n~ elements from ~n~ divisions of ~list~:
- inspired by source: user /arch/ from Uiua Discord
: ⌝⊏⍏◿<n>°⊏ <list>

Partition a string by spaces:
: ⊜□⊸≠@\s

Get the lowercase/uppercase alphabet:
: +⇡26@a
: +⇡26@A
Get the digits from 0-9 as a string:
: +⇡10@0

Linear interpolation (lerp):
: Lerp ← ⌅(
:   +⊃⊢(×/-) # normal <[min max]> <ratio> -> <result>
: | ÷⊃/-(-⊢) # inverse <[min max]> <result> -> <ratio>
: )

Upscale a 2d matrix or colored image by factor ~n~:
: ▽₂ <n><mat>
equivalent(?):
: ▽⟜≡▽ <n><mat>

Rotate a 2d matrix or colored image 90°:
: ⤸1

Separate an RGB image into its channels:
: °⊟₃⬚0⤸2_0_1_2 <img-arr>

Create a checkerboard of size N:
: ◿2⊞+.⇡ 8

Convert RGB array (e.g. ~[150 255 210]~) to hex code:
: ⊂@#♭˜⊏HexDigits≡⇌⊥[16 16]

Check for leap year:
: ↧↥⊃(=0◿400|≠0◿100|=0◿4)

Compactify coordinates in a matrix (bring them close together):
- source: user /shadow/ from Uiua Discord
: ⊸⍜⍉≡⍜⍆⊛

* Constants & Easter Eggs
See [[https://www.uiua.org/docs/constants][Constants]] for a list of all constants

Math:
: e (Euler) φ (golden ratio) γ (Euler-Mascheroni)
: r (real complex) i (imaginary)
: NaN (IEEE 754-2008) W (wildcard NaN → equals any other number)
: MaxInt (max. exact integer) ε (machine epsilon for Uiua)
: HexDigits (hexadecimal digits)

Adjacent neighbors offsets:
: A₁ A₂ A₃
Corner neighbors offsets:
: C₂ C₃
Edge neighbors offsets:
: E₃

Time:
: Days Months
: MonthDays LeapMonthDays

Placeholder Text (445 characters):
: Lorem

Colors:
: Black White
: => [0 0 0] [1 1 1]
: Red Green Blue
: => [1 0 0] [0 1 0] [0 0 1]
: Cyan Magenta Yellow
: => [0 1 1] [1 0 1] [1 1 0]
: Purple Orange
: => [0.5 0 1] [1 0.5 0]

System:
: ThisFile ThisFileName ThisFileDir
: WorkingDir

Images:
: Lena LenaDepth
: Cats CatsDepth
: Elevation
: Logo

Audio:
: Amen
: Music

[[https://en.wikipedia.org/wiki/Bad_Apple!!][Bad Apple!!]]
: Apple (frames at 24fps)
: Bad (audio)

Flags:
: Rainbow Lesbian Gay Bi Trans Pan Ace Aro AroAce Enby Fluid Queer Agender
: PrideFlags PrideFlagNames

Fun:
: Planets PlanetSymbols
: Zodiac ZodiacSymbols
: Suits Cards Chess
: Moon
: Skin People Hair
: Elements ElementSymbols

Easter eggs:
: # Boo!

JSON:
: True False
NULL pointer for use in ~&ffi~:
: NULL
